### PR TITLE
Markdown Editor compatible with Field: Multilingual Text Box

### PR DESCRIPTION
**Pull request by ranbureand**
Hello Jonas,

I started to use Github yesterday, so I’m a bit fumbling in the dark to pull this commit – I’ve no idea if this is the right modus operani for suggesting changes either, so please excuse my noobness.

I wanted to use your nice and synthetic Markdown Editor in combination with the Field: Multilingual Text Box, but the former was messing up the interface when installed:

http://www.andreaburan.com/workspace/files/markdown_editor_messed_up_interface_00.jpg

I dig a little in your code, I changed only a single line and after that the editor works properly. I tested it quickly in the default workspace of Symphony and it was working fine also for the standard textarea.

### CODE REVIEW

**Comment by klaftertief** [comment]
Thanks for reporting the bug and the pull request.
I've noticed this a couple of days ago as well and did exactly the same fix :-)
Though I'm also working on som other changes. So I won't merge it right now, but will incorporate it in the next release.

**Comment by ranbureand** [comment]
Oh, then I was too slow! >_< I’m happy to hear I did your very same fix: it means I finally started to “speak” Javascript! ;-) I’m looking forward for the next release of this extension! Thank you!

**Comment by klaftertief** [comment]
No, not to slow :-)
I just haven't published the changes yet.

**Comment by andrewminton** [comment]
Any update on applying these changes? Is there a commit I can pull for multilingual text box/field support? thanks

**Comment by nitriques** [comment]
I would appreciate this as well.

**Comment by klaftertief** [comment]
Sorry for not merging (a lot) earlier.
As mentioned above I wanted to add other changes... which I never did.

**Comment by klaftertief** [comment]
Ah, haven't tested this with the latest Mulitlingual Textbox. Can you confirm it's working? I'll create a new version then.
Thanks.

**Comment by ranbureand** [comment]
I just tested it with the latest version of the Multilingual Text Box and it works fine!

**Comment by nitriques** [comment]
I can confirm that it works like a charm. Thanks !!!

**Pull request merged**
